version: '3'
services:
  ekcp:
    environment:
      - HOST=0.0.0.0
      - PORT=8030
      - ROUTE_REGISTER=true
      - DOMAIN=nip.io
      - KUBEHOST=127.0.0.1 # Tweak this to your lan ip
    build: .
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    deploy:
      restart_policy:
        condition: on-failure
  gorouter:
    build: gorouter
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    links:
      - nats
    deploy:
      restart_policy:
        condition: on-failure
